// <auto-generated />
using System;
using CanIEatIt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanIEatIt.Migrations
{
    [DbContext(typeof(CanIEatItContext))]
    [Migration("20240807141653_EdibleUpdate3")]
    partial class EdibleUpdate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CanIEatIt.Models.Mushroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CapDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapDiameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Edible")
                        .HasColumnType("bit");

                    b.Property<string>("EdibleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GillDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LowerDiameter")
                        .HasColumnType("int");

                    b.Property<int?>("LowerHeight")
                        .HasColumnType("int");

                    b.Property<string>("MicroscopicDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SporeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpperDiameter")
                        .HasColumnType("int");

                    b.Property<int?>("UpperHeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mushroom");
                });
#pragma warning restore 612, 618
        }
    }
}
